apiVersion: operator.open-cluster-management.io/v1
kind: Klusterlet
metadata:
  name: klusterlet
spec:
  registrationImagePullSpec: registry.cn-beijing.aliyuncs.com/ocm/registration
  workImagePullSpec: registry.cn-beijing.aliyuncs.com/ocm/work
  clusterName: {{ .Name }}
  namespace: open-cluster-management-agent
  externalServerURLs:
    - url: {{ .HubInfo.APIServer }}