apiVersion: operator.open-cluster-management.io/v1
kind: Klusterlet
metadata:
  name: klusterlet
spec:
  registrationImagePullSpec: quay.io/open-cluster-management/registration
  workImagePullSpec: quay.io/open-cluster-management/work
  clusterName: {{ .Name }}
  namespace: open-cluster-management-agent
  externalServerURLs:
    - url: {{ .HubInfo.APIServer }}