apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ocm-register-assistant
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - namespaces
      - serviceaccounts
      - services
      - secrets
    verbs:
      - create
      - get
      - list
      - update
      - watch
      - patch
      - delete
  - apiGroups:
      - ""
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
      - patch
      - update
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
      - rolebindings
    verbs:
      - create
      - get
      - list
      - update
      - watch
      - patch
      - delete
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - roles
    verbs:
      - create
      - get
      - list
      - update
      - watch
      - patch
      - delete
      - escalate
      - bind
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
    verbs:
      - create
      - get
      - list
      - watch
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests/approval
    verbs:
      - update
  - apiGroups:
      - certificates.k8s.io
    resources:
      - signers
    resourceNames:
      - kubernetes.io/*
    verbs:
      - approve
  - apiGroups:
      - cluster.open-cluster-management.io
    resources:
      - managedclusters
    verbs:
      - get
      - list
      - watch
      - update
      - create
      - delete
  - apiGroups:
      - register.open-cluster-management.io
    resources:
      - managedclusters
      - managedclusters/accept
    verbs:
      - get
      - list
      - watch
      - update
      - create
      - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ocm-register-assistant
  namespace: open-cluster-management
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ocm-register-assistant
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ocm-register-assistant
subjects:
  - kind: ServiceAccount
    name: ocm-register-assistant
    namespace: open-cluster-management
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ocm-register-assistant
  namespace: open-cluster-management
spec:
  template:
    spec:
      containers:
        - name: register
          image: registry.cn-beijing.aliyuncs.com/ocm/register-assistant:v1
          imagePullPolicy: IfNotPresent
      restartPolicy: OnFailure
      serviceAccountName: ocm-register-assistant
